#!/bin/bash

# Symlink this to a location in your $path
# e.g. ln -s `pwd`/rsdns /usr/local/bin/rsdns

FILELOCATION=$0
while readlink "$FILELOCATION" > /dev/null
do
	FILELOCATION=$(readlink "$FILELOCATION")
done

LOCATION=$(dirname "$FILELOCATION")
COMMAND=$1
if [ "$COMMAND" ]
then
	shift
	$LOCATION/rsdns-$COMMAND.sh $@
else
	echo "Available commands:"
	cd $LOCATION
	(
		for COMMAND in $(ls rsdns-*.sh | sed "s/rsdns-\(.*\)\.sh/  \1/")
		do
			echo -n " $COMMAND | "
			./rsdns-$COMMAND.sh -w
		done
	) | column -t -s '|'
fi
